title: MEAlytics
description: MEAlytics user guide
baseurl: "/CureQ"
url: "https://cureq.github.io"

# Build settings
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-seo-tag
include:
  - docs